export const RouteUrls = {
    executivekpis: 'executivekpis',
    dashboard: 'dashboard',
    navigator: 'navigator',
    anomalies: 'anomalies',
    optimize: 'optimize',
    operate: 'operate',
    fileDownloads: 'filedownloads',
    fileTransfer: 'filetransfer',
    tagManager: 'tagmanager',
    organize: 'organize',
    businessGroupings: 'businessgroupings',
    cloudAccounts: 'cloudaccounts',
    spaces: 'spaces',
    workloads: 'workloads',
    resourcePools: 'resourcepools',
    vLabels: 'vlabels',
    vScore: 'vscore',
    recommendations: 'recommendations',
    takeAction: 'takeaction',
    vPolicies: 'vpolicies',
    quotasBudgets: 'quotasbudgets',
    resources: 'resource',
    resourcesDetail: 'resource/:id',
    tagManagement: 'tagmanagement',
    forecasting: 'forecasting',
    parking: 'parking',
    alerting: 'alerting',
    contacts: 'contacts',
    hushes: 'hushes',
    myFiles: 'myfiles',
    helpSupport: 'helpsupport',
    settings: {
        url: 'settings',
        tabs: [
            { label: 'My Profile', id: 'profile' },
            { label: 'Password', id: 'password' },
            { label: 'Users', id: 'users' },
            { label: 'Roles & Permissions', id: 'permissions' },
            { label: 'Provider Accounts', id: 'accounts' },
            { label: 'Multi-Factor Authentication', id: 'mfa' },
            { label: 'Single Sign-On', id: 'sso' },
            // { label: 'Notifications', id: 'notifications' },
        ],
    },
    cloudHeroes: 'cloudheroes',
    cloudHeroBadges: 'cloudherobadges',
    cloudHeroSummaries: 'cloudherosummaries',
};
